### ISSUE TITLE
for mobile games

### ISSUE THREAD

**Issue by ccfiel** [skool51/shellyjs#4]
Hello,

Can this be used for mobile games?

Cheers,
Chris

**Comment by sdale511** [comment]
Yes - we are currently using it for a turn based realtime Andriod/iOS game.

I’m just about to dust this off for the backend.  It should be getting a lot of polish in the next few weeks.

-- 
Scott Dale

On January 9, 2015 at 3:11:31 PM, Chris Ian Fiel (notifications@github.com) wrote:

Hello,

Can this be used for mobile games?

Cheers,
Chris

**Comment by ccfiel** [comment]
Scott,

Wow that's great! we will try to used to our mobile game  :+1:

**Comment by sdale511** [comment]
We have an updated version that we are about to check-in - current tip has some pretty stale nom versions and is broke on PC.

We are definitely going to put some energy into it.  Will be a few bumps until we get some production miles on it, but we are shooting for a better then SmartFox node.js backend.

-- 
Scott Dale

On January 9, 2015 at 4:15:00 PM, Chris Ian Fiel (notifications@github.com) wrote:

Scott,

Wow that's great! we will try to used to our mobile game

**Comment by ccfiel** [comment]
@sdale511 Nice. I can't wait to test the updated version :)
